version: "3.8"
services:
  application:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/roommate:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=roommate"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    env_file:
      - .env